name: Deploy Pages

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  strategy:
    matrix:
      node-version: ['20.x']
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/dashboard

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: yarn build

      - uses: actions/upload-artifact@v3
        with:
          name: dashboard
          path: build/client

      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/client

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
